### ISSUE TITLE
Possibility to show last modification date (of a file) with the parent folder

### ISSUE THREAD

**Issue by tobiwollender** [xperseguers/t3ext-file_list#1]
I just switched from the old pi1 plugin version and miss one "feature". In the old system it was possible to show the last modification date of a folder (and not only how many files are in). The date should reflect the date, when a file in a folder (or subfolder) was last modified. So I don't mean the modification date of the folder itself.

Is this possible already and I just miss the needed variable? If not, maybe you can consider adding this as a new feature.

**Comment by xperseguers** [comment]
This is unfortunately not possible anymore since the FAL from TYPO3 does not provide such information anymore.
