### ISSUE TITLE
Label for general tab

### ISSUE THREAD

**Issue by buezu09** [xperseguers/t3ext-file_list#11]
Hi @xperseguers, since TYPO3 version 9.3 the language files are moved from ext:lang and ext:lang is removed completly. The flexform reference to `EXT:lang/locallang_core.xlf:labels.generalTab` which results in a mistake. Is it possible to change the reference to `EXT:core/Resources/Private/Language/locallang_core.xlf:labels.generalTab` ?

Regards
buezu09
![file_list](https://user-images.githubusercontent.com/8806978/64592131-97bb1780-d3ab-11e9-8b81-aaff3407f6e1.png)

**Comment by aceArt-GmbH** [comment]
@buezu09 we created a pull request. If you using composer you can use our repository for the meantime. Thank you for your help with the label.

```
  "repositories": [
      { "type":"vcs", "url": "https://github.com/aceArt-GmbH/t3ext-file_list" }
   ],
   "require": {
      "causal/file_list": "dev-master",
   }
```
