### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by marcelbirrer** [xperseguers/t3ext-file_list#14]
When activating the checkbox «allow Subfolders» in the flexorm, following error occurs in the frontend:

Causal\FileList\Controller\FileController ERROR:
The configuration of the file_list plugin is incorrect: Serialization of 'Closure' is not allowed

**Comment by marcelbirrer** [comment]
maybe another unsupported file format? .xslx?

**Comment by xperseguers** [comment]
Which version of TYPO3?

**Comment by marcelbirrer** [comment]
8.7.30

**Comment by xperseguers** [comment]
Strange, I'm using it actively, tested right away, I don't know how to reproduce. Please enable debug mode / context and edit file `Classes/Controller/FileController.php` around line 159:

```
return $this->error('The configuration of the file_list plugin is incorrect: ' . $e->getMessage());
```

to read:

```
throw $e;
```

and report where the error comes actually from.

**Comment by xperseguers** [comment]
Regarding your comment on January 16th with "wrong file format", if you are referring to the other ticket #13, then please read what was wrong with the author's configuration.

**Comment by xperseguers** [comment]
Sure it's not related to this extension but to some misconfiguration.
