### ISSUE TITLE
File List 2.4 doesn't display any file from folder

### ISSUE THREAD

**Issue by sylvainhemmer** [xperseguers/t3ext-file_list#16]
Since updating from version 2.3 to version 2.4 of the extension, displaying files from a folder on the front-end doesn't work anymore. The only message displayed is the following:

`No files or folders found in this directory!`, but files do exist in the folder.

TYPO3 version: 9.5.14

**Comment by karelkuijpers** [comment]
I have the same problem. In the function filterInaccessibleFiles of the utility Helper is checked on property "Isvisible". When this property does not exists the file is excluded. The function should first perform the test if ($file->hasProperty('visible')).

**Comment by xperseguers** [comment]
I see, there is a requirement for EXT:filemetadata (system extension)
