### ISSUE TITLE
Can't add File List as a content element in the back-end

### ISSUE THREAD

**Issue by sylvainhemmer** [xperseguers/t3ext-file_list#17]
Since updating from version 2.3 to version 2.4 of the extension, the extension File List doesn't appear in the list of available content elements anymore. Example:

![image](https://user-images.githubusercontent.com/60656850/75761778-f00b1a80-5d39-11ea-8ade-92094c6ef969.png)

Using version 2.3:
![image](https://user-images.githubusercontent.com/60656850/75762022-509a5780-5d3a-11ea-9a62-8f45282fcb6e.png)

TYPO3 version: 9.5.14

**Comment by xperseguers** [comment]
This is indeed a TODO which has been done for TYPO3 v9 as part of commit c229fc5692f76e9b76761390cfa2f23ce3d07bc1
