### ISSUE TITLE
Security fix for TYPO3 6.2?

### ISSUE THREAD

**Issue by Gitsko** [xperseguers/t3ext-file_list#19]
Hi,

is there a security fix for TYPO3 6.2? Or can i fix with an git patch (commit) ?

**Comment by xperseguers** [comment]
No, there is no security fix for TYPO3 6.2 as v6.2 is for long not supported anymore but it's easy for you to patch it on your own by having a look at what was actually fixed in version 2.3.2:

https://github.com/xperseguers/t3ext-file_list/compare/2.3.1...2.3.2
