### ISSUE TITLE
FileIconViewHelper throw exception, because of File|FileReference annotation of render method

### ISSUE THREAD

**Issue by mediaessenz** [xperseguers/t3ext-file_list#2]
It seems TYPO3 8.7 uses this annotation for doing some "magic" stuff.
Because of there are two kinds, it not work out and finally throws this exception:
The argument "file" was registered with type "File|FileReference", but is of type "TYPO3\CMS\Core\Resource\File" in view helper "Causal\FileList\ViewHelpers\FileIconViewHelper"

If you change it from "File|FileReference" to "object", it works fine.

**Comment by xperseguers** [comment]
Thanks for reporting. Please check PR.

**Comment by mediaessenz** [comment]
I have tested your PR and can confirm that this fixes #2
