### ISSUE TITLE
Utility  > Helper > $file->getProperty('fe_groups'), property does no exists

### ISSUE THREAD

**Issue by lucmuller** [xperseguers/t3ext-file_list#33]
Not sure I'm missing somthing, but fe_groups property doesn't seems to exists in default TYPO3 installation (v10).

The code should test if the file has the property unless it breaks.

**Comment by lucmuller** [comment]
`if($file->hasProperty('fe_groups')){
                    $accessGroups = $file->getProperty('fe_groups');
                    if (!empty($accessGroups)) {
                        $accessGroups = GeneralUtility::intExplode(',', $accessGroups, true);
                        if (empty(array_intersect($accessGroups, $userGroups))) {
                            continue;
                        }
                    }
                }`

**Comment by lucmuller** [comment]
if this seems correct to you. I'll try to provide a fix for this.

**Comment by xperseguers** [comment]
your code is hard to read, you may have used a single backtick (for inline code) instead of 3.

It looks like `fe_groups` is provided by EXT:filemetadata. Since I cannot think of a TYPO3 install without it, I didn't spot that :)

You can provide a patch, will review. Thanks

**Comment by lucmuller** [comment]
In your opinion, what would be the best fix ?
Testing if the property exists, or maybe you should add the dependancy to EXT:filemetadata ?

**Comment by xperseguers** [comment]
I'd say it's the only "special property" I'm using so testing for availability sounds reasonable, no need to add a dependency if not really needed, I prefer to stay as lightweight as possible with my extensions.
