### ISSUE TITLE
Error Call to a member function modifyLinkAttributes() on null

### ISSUE THREAD

**Issue by helmut-winkelbach** [xperseguers/t3ext-file_list#42]
On file_list 2.5.0., dev from Github.
Installation on TYPO3 11.5.13, if i try to cal the link to the folder, or file collections, i get the following error: Call to a member function modifyLinkAttributes() on null.

For more information, see Whoops, looks like something went wrong.
[Whoops.docx](https://github.com/xperseguers/t3ext-file_list/files/9126485/Whoops.docx)

**Comment by xperseguers** [comment]
Must have been a bug in TYPO3 Core. I cannot reproduce.
