### ISSUE TITLE
Version 2.2.3 leads to uncaught TYPO3-Exception

### ISSUE THREAD

**Issue by beath** [xperseguers/t3ext-file_list#5]
With version 2.2.3 there is an uncaught exception in the frontend (every page with the plugin on it).
```
Uncaught TYPO3 Exception
Section "Main" does not exist.
```

**Comment by xperseguers** [comment]
Don't know how to reproduce. Please enable Development mode and show the stack trace for instance.

**Comment by xperseguers** [comment]
I suspect you have overridden the default templates but not the default layout and you probably need to adapt either of them to be in line with default templates/layout provided by the "new" version of this extension.

**Comment by beath** [comment]
Could very well be.
