### ISSUE TITLE
RuntimeException: listAction did not return an instance of Psr\Http\Message\ResponseInterface

### ISSUE THREAD

**Issue by m10a** [xperseguers/t3ext-file_list#51]
Hi,
I get the following error, when I use the file collections mode. In folder mode everything works fine:

`Controller action Causal\FileList\Controller\FileController::listAction did not return an instance of Psr\Http\Message\ResponseInterface.`

The error occurs in TYPO3 12 in both mode composer and non-composer.

**Comment by xperseguers** [comment]
Which version are you running? Latest release (3.0.1) contains the code to return such a response since TYPO3 v11 in that method.

**Comment by m10a** [comment]
3.0.1 on TYPO3 12.4.11
