### ISSUE TITLE
Version 3.0.1: upgrade wizard fails with "Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchOne"

### ISSUE THREAD

**Issue by tobiasschaeferptb** [xperseguers/t3ext-file_list#52]
Hi,

my setup is TYPO3 10.4.37, php 7.4.33, MariaDB 10.6.15. After updating Ext:file_list from version 2.7.0 to 3.0.1 the upgrade wizard fails with this exception:
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchOne() | Error thrown in file /typo3conf/ext/file_list/Classes/Updates/PluginsUpdater.php in line 110`
The exception happens after clicking on the "Run Upgrade Wizard" button.

Any ideas what is going wrong?

Best regards,
Tobias Schäfer

**Comment by xperseguers** [comment]
Is it possible that you do not run a composer-based installation of TYPO3? I may remember someone reporting that zip/tar.gz releases of TYPO3 do not have the same version of Doctrine, but unsure.

**Comment by xperseguers** [comment]
Note: you may try to change the `->fetchOne()` call to (iirc) `->fetchColumn()` or `->fetchColumn(0)` which should be the same.

**Comment by tobiasschaeferptb** [comment]
Hello Xavier,

sorry that I forgot to mention if it's a classic or composer installation. It's a classic. After changing fetchOne() to fetchColumn() the error doesn't occur anymore but there is a new error when I click on the "Perform updates!" button:
`Uncaught TYPO3 Exception: Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAllAssociative() | Error thrown in file /typo3conf/ext/file_list/Classes/Updates/PluginsUpdater.php in line 52`
In typo3_src-10.4.37/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php there is a fetch and a fetchAll methode. Which methode could be used instead of fetchAllAssociative?
In typo3_src-10.4.37/vendor/doctrine/dbal/lib/Doctrine/DBAL/Version.php the doctrine version is defined as 2.10.4.

Best regards,
Tobias Schäfer

**Comment by xperseguers** [comment]
Really strange that the same version of Doctrine is not bundled "correctly". Anyway, then you can manually change `->fetchAssociative()` as `->fetch()` and `->fetchAllAssociative()` as `->fetch()`.

... and think about switching to composer ;-)

**Comment by tobiasschaeferptb** [comment]
This worked. Thank you!
