### ISSUE TITLE
Feature request: Sort by none

### ISSUE THREAD

**Issue by ceekay73** [xperseguers/t3ext-file_list#57]
Hello,
I'm using file_list to display file collections which are already sorted manually. So the default sort by name does not show me rhe display order i want. 

Up until now I manually altered the controller and flexform with a sort by none option, but with composer based install now I would have to propery extend via own extension - or simply ask you to add this feature ;-) 

Kind regards, Christoph

**Comment by xperseguers** [comment]
If you did the job in the past, maybe you could suggest a PR right away?
