### ISSUE TITLE
Section "Main" does not exist. TYPO3 8.7.24 and File List 2.3.0 and 2.3.1

### ISSUE THREAD

**Issue by seitenweiseUDO** [xperseguers/t3ext-file_list#7]
i just updated file_list from 2.2.2 to 2.3.0 and/or 2.3.1. with both version i'm getting the folling error: Section "Main" does not exist.

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Section "Main" does not exist. | TYPO3Fluid\Fluid\View\Exception\InvalidSectionException thrown in file /typo3_src/vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php in line 269.

2.2.2 ist running fine…and help would be appreciated.
thanks a lot.

**Comment by xperseguers** [comment]
This duplicates #5, please check there for info.

**Comment by seitenweiseUDO** [comment]
hi xavier,
thanks a lot. everything works again.
regards.
udo.
